language: python

python:
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install coveralls

script: make test PYTEST_EXTRA_ARGS="--cov=giftless"

after_success:
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip
